### ISSUE TITLE
Increase max number of word per page

### ISSUE THREAD

**Issue by edouard-lopez** [JorisKok/minitranslate#1]
Hello, thanks for the addon it's really a nice way to introduce new vocabulary.

Could you increase the maximum number of word per page, as `10` is pretty low 

Keep the good work ❤️ !

**Comment by Kottakji** [comment]
Hello Édouard,


Thanks for your suggestion. I really appreciate it.


I will try to work on increasing the 10 words to a bit more as soon as I have time. Maybe to 20 or so, it's mostly performance wise that I didn't increase it, so I will have to try to improve the performance a bit as well. I will let you know when it's updated.

Joris Kok

________________________________
Van: Édouard Lopez <notifications@github.com>
Verzonden: maandag 27 november 2017 21:19
Aan: JorisKok/minitranslate
CC: Subscribed
Onderwerp: [JorisKok/minitranslate] Increase max number of word per page (#1)


Hello, thanks for the addon it's really a nice way to introduce new vocabulary.

Could you increase the maximum number of word per page, as 10 is pretty low

Keep the good work

**Comment by Kottakji** [comment]
I have changed the number to 20 and increased the speed of the addon (by a lot), by converting everything to indexedDB. You can select 20 now, but it won't likely find 20, but it will find as much as possible. Some words, like "using" and other verbs that are found converted within a text, are not easily found in the database I am using. They are found as "to use" in the database, so it is a bit hard to work on that. When I find more time, I will try to add better verb support. Cheers.
