### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by edouard-lopez** [JorisKok/minitranslate#2]
**related:** #1 

From my use it seems your processing is blocking page interaction, I reckon that' why you limit to 10 word / page.

This is probably due to the algorithm you use to insert your item.

You should have a look at [Characterizer's Chrome extension](https://chrome.google.com/webstore/detail/characterizer/ogidmabmpgbedcakjoiojmjbnnbkioig?hl=en-US), which offer a similar feature, and last time I check didn't had that bottleneck.

**Comment by Kottakji** [comment]
Ok thanks. Working on it. I will get rid of it blocking the DOM and also want to change it to Indexed DB, which should help with performance as well. 

Cheers

**Comment by Kottakji** [comment]
It should now work without blocking firefox. On installing the app, it does need a bit more time to initialize the database though.
